gurt.select('#register'):on('click', function()
    gurt.location.goto("gurt://arsonflare.aura/register")
end)
gurt.select('#login1'):on('click', function()
    gurt.location.goto("gurt://arsonflare.aura/login")
end)
gurt.select('#register1'):on('click', function()
    gurt.location.goto("gurt://arsonflare.aura/register")
end)

 
gurt.select('#discord'):on('click', function()
    gurt.location.goto("https://discord.gg/a4GVk5gbxv")
end)
gurt.select('#docs'):on('click', function()
    gurt.location.goto("gurt://arsonflare.aura/docs")
end)
gurt.select('#docs2'):on('click', function()
    gurt.location.goto("gurt://arsonflare.aura/docs")
end)